# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Book.create(name: 'Jungle King', author: 'John Doe', genre: 'Action and adventure', quantity: 50, published_date: '2016-12-20', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")
Book.create(name: 'Tiger King', author: 'Brandon Brown', genre: 'Fairytale', quantity: 5, published_date: '2011-10-12', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")
Book.create(name: 'Warrior', author: 'Kim LI', genre: 'History', quantity: 50, published_date: '2018-01-08', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")
Book.create(name: 'Classmates', author: 'Jiji Jojo', genre: 'Comedy', quantity: 70, published_date: '2011-05-14', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")
Book.create(name: 'Gossip Girl', author: 'Benjamin Jr', genre: 'Horror', quantity: 22, published_date: '2014-03-04', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")
Book.create(name: 'Sigma Rule', author: 'Dr. Man', genre: 'Thriller', quantity: 101, published_date: '2019-02-20', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")
Book.create(name: 'Silly Neighboors', author: 'Andrea Rossi', genre: 'Comedy', quantity: 44, published_date: '2016-07-18', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")
Book.create(name: 'The Legend', author: 'Dr. Man', genre: 'Thriller', quantity: 50, published_date: '2016-09-12', description: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.")